version: '3.7'
services:
  rb:
    build: ./assets/rb
    image: myruby3.0
    container_name: myruby3.0
    tty: true
    volumes:
      - ./PV/rb/app/:/usr/src/app/
    command: >
      bash -c '
        bundle install
        while true; do sleep 3600; done
      '
